spring.application.name=bff
server.port=${BFF_PORT:8080}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}

services.pedidos.url=${PEDIDOS_SERVICE_URL:http://localhost:8082}
services.productos.url=${PRODUCTOS_SERVICE_URL:http://localhost:8081}

cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:4200}
